# Generated by Django 6.0.6 on 2026-06-29 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Coach_Headshot', models.ImageField(upload_to='coach_headshots')),
                ('Coach_First_Name', models.CharField(max_length=25)),
                ('Coach_Last_Name', models.CharField(max_length=25)),
                ('Coach_Role', models.CharField(choices=[('HC', 'Head-Coach'), ('AC', 'Assistance-Coach'), ('O', 'Offense'), ('D', 'Defense'), ('G', 'Goalie'), ('FC', 'Face-off')], max_length=25)),
                ('programs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_coach', to='programs.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
