# Generated by Django 6.0.6 on 2026-06-29 18:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='Short Key for identifying program', max_length=5)),
                ('programImage', models.ImageField(upload_to='programimages')),
                ('name', models.CharField(help_text="Program's Full Name", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('program_active', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['key'], name='program_key')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of Team inside of Program Varsity, JV, U14A,U14B etc', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('practice_start_date', models.DateField(default=django.utils.timezone.now)),
                ('practice_end_date', models.DateField(default=django.utils.timezone.now)),
                ('practice_location', models.CharField(max_length=100)),
                ('programs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='programs.program')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
