# Generated by Django 6.0.6 on 2026-06-29 18:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playerHeadshot', models.ImageField(upload_to='playerheadshots')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('player_position', models.CharField(choices=[('A', 'Attack'), ('M', 'Midfield'), ('D', 'Defense'), ('G', 'Goalie'), ('LSM', 'Long Stick Midfield'), ('SSDM', 'Short Stick Defensive Midfield'), ('FOGO', 'Face-off Specialist')], max_length=40)),
                ('player_year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], max_length=8)),
                ('playerUni_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team', to='programs.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
